# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(759, 483)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.developer_info = QtWidgets.QTextBrowser(Dialog)
        self.developer_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.developer_info.sizePolicy().hasHeightForWidth())
        self.developer_info.setSizePolicy(sizePolicy)
        self.developer_info.setStyleSheet("")
        self.developer_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setReadOnly(True)
        self.developer_info.setOpenExternalLinks(True)
        self.developer_info.setObjectName("developer_info")
        self.verticalLayout.addWidget(self.developer_info)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.warlordsoft_button = QtWidgets.QPushButton(Dialog)
        self.warlordsoft_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warlordsoft_button.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myresource/resource/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warlordsoft_button.setIcon(icon)
        self.warlordsoft_button.setObjectName("warlordsoft_button")
        self.horizontalLayout_14.addWidget(self.warlordsoft_button)
        self.donate_button = QtWidgets.QPushButton(Dialog)
        self.donate_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.donate_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myresource/resource/paypal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donate_button.setIcon(icon1)
        self.donate_button.setObjectName("donate_button")
        self.horizontalLayout_14.addWidget(self.donate_button)
        self.rate_button = QtWidgets.QPushButton(Dialog)
        self.rate_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rate_button.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/myresource/resource/facebook-like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rate_button.setIcon(icon2)
        self.rate_button.setObjectName("rate_button")
        self.horizontalLayout_14.addWidget(self.rate_button)
        self.feedback_button = QtWidgets.QPushButton(Dialog)
        self.feedback_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_button.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/myresource/resource/person-growth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_button.setIcon(icon3)
        self.feedback_button.setObjectName("feedback_button")
        self.horizontalLayout_14.addWidget(self.feedback_button)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.developer_info.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/myresource/resource/icons8-male-user-96.png\" height=\"50\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#35a849;\">Developed by: </span><span style=\" font-weight:600; color:#35a849;\">Rishabh Bhardwaj</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#35a849;\">Version: </span><span style=\" font-weight:600; color:#35a849;\">0.2 | </span><a href=\"https://snapcraft.io/search?q=rishabh\"><span style=\" font-weight:600; text-decoration: underline; color:#ef2929;\">Get more apps</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#35a849;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#35a849;\">Support Request:</span><span style=\" color:#35a849;\">   If you like this Application, then please support the developer by donation. Your donations make me </span><span style=\" font-weight:600; color:#35a849;\">feel motivated</span><span style=\" color:#35a849;\"> to my work. Thanks!  Expect </span><span style=\" font-weight:600; color:#35a849;\">new updates</span><span style=\" color:#35a849;\"> in near future!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#35a849;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#35a849;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#35a849;\">Donor\'s Name</span><span style=\" color:#35a849;\"> and Contributions will be displayed in @ </span><a href=\"https://warlordsoftwares.com/warlord_soft/our_contributors/\"><span style=\" font-weight:600; text-decoration: underline; color:#ef2929;\">warlordsoft page</span></a><span style=\" color:#35a849;\"> as a Thanksgiving notes!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#35a849;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#35a849;\"><br /></p></body></html>"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/myresource/resource/pdf2go.png\" height=\"50\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#35a849;\">PDF2OCR FOR LINUX (OCR based free reader)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#35a849;\">Version 1.11</span></p></body></html>"))
        self.warlordsoft_button.setText(_translate("Dialog", "Visit @WarlordSoft"))
        self.donate_button.setText(_translate("Dialog", "Donate"))
        self.rate_button.setText(_translate("Dialog", "Rate"))
        self.feedback_button.setText(_translate("Dialog", "Feedback"))
import resource_rc
