name: pdf2go
base: core18 # the base snap is the execution environment for this snap
version: '2024.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Convert pdf or image into text using OCR
description: A linux based desktop application for converting image/pdf into plain text format using OCR
grade: stable # must be 'stable' to release into candidate/stable channels  / before dev use devel
confinement: strict # use 'strict' once you have the right plugs and slots / before dev use devmode

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

apps:
  pdf2go:
    command: bin/desktop-launch python3 $SNAP/pdf2go.py
    plugs: 
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - optical-drive
       - removable-media
    desktop: pdf2go.desktop
    environment:
      TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
      DISABLE_WAYLAND: 1

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime-lite:
    interface: content
    target: $SNAP/pyqt5-runtime-lite
    default-provider: pyqt5-runtime-lite


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/pdf2go.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/pdf2go.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/pdf2go.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  pdf2go:
      plugin: python
      python-version: python3
      source: .
      python-packages: 
          - googletrans==4.0.0rc1
          - pytesseract
          - pdf2image
          - PyPDF2<3.0
          - requests
          - cryptography
      build-attributes: [ keep-execstack ]
      stage-packages:
        - poppler-utils
        - tesseract-ocr
