name: pdf2go
base: core22
version: '2026.7.2'
summary: Convert pdf or image into text using OCR
description: A linux based desktop application for converting image/pdf into plain text format using OCR
confinement: strict

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/pyqt5-runtime-core22-lite

apps:
  pdf2go:
    command: bin/desktop-launch python3 $SNAP/pdf2go.py
    plugs: 
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - optical-drive
       - removable-media
    desktop: pdf2go.desktop
    environment:
      TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
      DISABLE_WAYLAND: 1

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime-core22-lite:
    interface: content
    target: $SNAP/pyqt5-runtime-core22-lite
    default-provider: pyqt5-runtime-core22-lite


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/pdf2go.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/pdf2go.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/pdf2go.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  pdf2go:
      plugin: python
      source: .
      python-packages: 
          - googletrans==4.0.0rc1
          - pytesseract
          - pdf2image
          - PyPDF2<3.0
          - requests
          - cryptography
      stage-packages:
        - poppler-utils
        - tesseract-ocr
